import type { TemplateLayout } from '../../../types/template';

export const defaultGithubTemplate: TemplateLayout = {
  id: 'github-dashboard-reference',
  name: 'GitHub Home Template',
  description: 'GitHub home layout rebuilt with local placeholder blocks.',
  source: 'default',
  version: 2,
  activeScreenId: 'github-home',
  screens: [
    {
      id: 'github-home',
      name: 'GitHub Home',
      providerRoute: 'github.com/',
      description: 'Logged-in GitHub dashboard home screen with placeholder content.',
    },
  ],
  regions: ['topbar', 'left-sidebar', 'main-feed', 'right-sidebar'],
  metadata: {
    provider: 'github',
    browserMappingKey: 'github.dashboard.reference',
    updatedAt: '2026-04-23',
  },
  blocks: [
    {
      id: 'top-nav',
      type: 'top-nav',
      title: 'Global Header',
      region: 'topbar',
      screenId: 'github-home',
      visible: true,
      extensionSlot: 'github.global.header',
      props: {
        context: 'Dashboard',
        searchPlaceholder: 'Type / to search',
        links: [],
        actions: ['Copilot', 'Create', 'Issues', 'Pull requests', 'Repositories', 'Inbox'],
      },
    },
    {
      id: 'profile-summary',
      type: 'profile-summary',
      title: 'Account Context',
      region: 'left-sidebar',
      screenId: 'github-home',
      visible: true,
      extensionSlot: 'github.dashboard.account',
      props: {
        name: 'alex-placeholder',
        handle: 'Personal dashboard',
        bio: '',
        stats: [],
      },
    },
    {
      id: 'recent-repos',
      type: 'recent-repos',
      title: 'Top Repositories',
      region: 'left-sidebar',
      screenId: 'github-home',
      visible: true,
      extensionSlot: 'github.dashboard.repositories.top',
      props: {
        searchPlaceholder: 'Find a repository...',
        repositories: [
          { name: 'alex-placeholder/ui-workbench', language: 'TypeScript', visibility: 'Public' },
          { name: 'alex-placeholder/git-notes', language: 'Markdown', visibility: 'Private' },
          { name: 'reflow-labs/layout-capture', language: 'React', visibility: 'Public' },
          { name: 'demo-space/issue-board', language: 'JavaScript', visibility: 'Public' },
          { name: 'alex-placeholder/browser-mapper', language: 'CSS', visibility: 'Private' },
          { name: 'design-systems/token-playground', language: 'TypeScript', visibility: 'Public' },
          { name: 'sample-org/primer-copy', language: 'TypeScript', visibility: 'Public' },
          { name: 'alex-placeholder/home-feed', language: 'JavaScript', visibility: 'Public' },
        ],
      },
    },
    {
      id: 'copilot-prompt',
      type: 'copilot-prompt',
      title: 'Assistant Prompt',
      region: 'main-feed',
      screenId: 'github-home',
      visible: true,
      extensionSlot: 'github.dashboard.copilot.prompt',
      props: {
        placeholder: 'Ask anything or type @ to add context',
        model: 'Claude Haiku 4.5',
        chips: ['Agent', 'Create issue', 'Write code', 'Git', 'Pull requests'],
      },
    },
    {
      id: 'activity-feed',
      type: 'activity-feed',
      title: 'Home Feed',
      region: 'main-feed',
      screenId: 'github-home',
      visible: true,
      extensionSlot: 'github.dashboard.feed',
      props: {
        filters: ['Filter'],
        events: [
          {
            actor: 'octo-demo',
            action: 'released',
            subject: 'placeholder-ui v2.4',
            time: '20m',
            summary: 'A compact release note with a short description, repository link, and muted metadata.',
          },
          {
            actor: 'maple-labs',
            action: 'opened pull request',
            subject: 'Add selector scoring fallback',
            time: '1h',
            summary: 'Improves matching when source pages change class names and layout landmarks.',
          },
          {
            actor: 'northstar-labs',
            action: 'starred',
            subject: 'browser-layout-capture',
            time: '3h',
            summary: 'A utility package for turning page regions into editable schema.',
          },
        ],
      },
    },
    {
      id: 'repo-updates',
      type: 'repo-updates',
      title: 'Repository Updates',
      region: 'main-feed',
      screenId: 'github-home',
      visible: true,
      extensionSlot: 'github.dashboard.repository.updates',
      props: {
        updates: [
          { repo: 'reflow-labs/layout-capture', message: 'Published a preview build with better sidebar detection.', status: 'Release' },
          { repo: 'alex-placeholder/ui-workbench', message: 'Merged compact empty-state components for feed cards.', status: 'Merged' },
          { repo: 'sample-org/primer-copy', message: 'Added a smaller changelog card and muted timeline text.', status: 'Release' },
        ],
      },
    },
    {
      id: 'pinned-repos',
      type: 'pinned-repos',
      title: 'Pinned Repositories',
      region: 'main-feed',
      screenId: 'github-home',
      visible: false,
      extensionSlot: 'github.dashboard.repositories.pinned',
      props: {
        repositories: [
          {
            name: 'layout-capture',
            description: 'Placeholder repository card for future block mapping.',
            language: 'TypeScript',
            stars: '1.2k',
          },
          {
            name: 'template-runtime',
            description: 'Composable React renderer for saved page layouts.',
            language: 'React',
            stars: '842',
          },
        ],
      },
    },
    {
      id: 'issue-pr-updates',
      type: 'issue-pr-updates',
      title: 'Issues and Pull Requests',
      region: 'right-sidebar',
      screenId: 'github-home',
      visible: false,
      extensionSlot: 'github.dashboard.work.queue',
      props: {
        items: [
          { label: 'Assigned issues', count: 6 },
          { label: 'Review requests', count: 3 },
          { label: 'Mentioned threads', count: 9 },
        ],
      },
    },
    {
      id: 'trending-repos',
      type: 'trending-repos',
      title: 'Latest from our changelog',
      region: 'right-sidebar',
      screenId: 'github-home',
      visible: true,
      extensionSlot: 'github.dashboard.changelog',
      props: {
        repositories: [
          { name: 'GitHub Copilot for Jira: Our latest enhancements', language: 'Changelog', stars: '7 hours ago' },
          { name: 'Copilot code review user counts now aggregate in usage metrics API', language: 'Changelog', stars: '8 hours ago' },
          { name: 'GitHub CLI: Opt-out usage telemetry', language: 'Changelog', stars: '9 hours ago' },
          { name: 'Bring your own language model key in VS Code now available', language: 'Changelog', stars: '15 hours ago' },
        ],
      },
    },
    {
      id: 'recommended-repos',
      type: 'recommended-repos',
      title: 'Explore Repositories',
      region: 'right-sidebar',
      screenId: 'github-home',
      visible: false,
      extensionSlot: 'github.dashboard.explore.repositories',
      props: {
        repositories: [
          { name: 'placeholder/feed-patterns', reason: 'Because you work with dashboard layouts.' },
          { name: 'example/repo-discovery', reason: 'Popular with frontend extension teams.' },
        ],
      },
    },
  ],
};
